#!/usr/bin/env python

from os import geteuid, path, chdir
from commands import *
from args import get_args

CONFIG_PATH = "/etc/stopro/conf.yml"

def check_root():
    if geteuid() != 0:
        print("You need root permission")
        exit(1)

def main():
    check_root()
    config = load_config(CONFIG_PATH)
    arguments = get_args()
    if arguments.command == "start":
        cmd_start()
    elif arguments.command == "stop":
        cmd_stop()
    elif arguments.command == "status":
        cmd_status()

if __name__ == "__main__":
    main()

