#!/usr/bin/env python

from os import geteuid, path, chdir
from sys import argv
from utils import *

CONFIG_PATH = "/home/john/.config/stopro/conf.yml"

def check_root():
    if geteuid() != 0:
        print("You need root permission")
        exit(1)

def main():
    check_root()
    config = load_config(CONFIG_PATH)
    if len(argv) < 2:
        print_help()
        exit(0)
    command = argv[1].lower()
    if command == "start":
        backup_hosts()
        forbid_sites(config["forbidden_sites"])
    elif command == "stop":
        apply_backup()
    else:
        print_help()

if __name__ == "__main__":
    main()

